### ISSUE TITLE
Pretty serious anchoring bug causes spurious matches

### ISSUE THREAD

**Issue by vlovich** [mherrmann/gitignore_parser#10]
.gitignore contents:
build

`<path to project>/abcbuild` matches even though such a pattern is supposed to only match if the file name is exactly that.

**Comment by mherrmann** [comment]
I'll be happy to accept a PR that fixes

**Comment by vlovich** [comment]
Posted the PR although I don't know the spec well enough. https://github.com/snark/ignorance/issues/1 has a different proposal for anchoring. Can you let me know which solution is correct?

**Comment by mherrmann** [comment]
I'm afraid I don't know which solution is correct. I also don't have time to look into it. You mention in your PR that you are not entirely sure it is the right behavior. I would love to have a more confident opinion, by either you or others, that your proposed change really conforms to the spec.

**Comment by bitranox** [comment]
since I need a quick working solution, I made a fork ... 
@hermann - I really dont want to make a hostile takeover, but You seem to be busy with other things - so I made a quick fork.
I will be happy to pass it back to You after quickly moving forward and stabilisation period. 

@vlovich - check out https://github.com/bitranox/igittigitt 
and make Your PRs against that repo, I need to move on quickly.

**Comment by Azmisov** [comment]
I believe a ran into this same issue:
```
# .gitignore
build/
```
will match both `build/` directory and `sdist_build.py`

**Comment by thebaptiste** [comment]
Hello
Is this issue fixed ?

**Comment by jacky1234** [comment]
I have a issue like this:
A project managed by git. And the gitignore config like this: '*/build'. 
And the file abs path like: ./B/build/a.java is not ignored!

**Comment by mherrmann** [comment]
This was probably resolved by #58.
